### ISSUE TITLE
yaml 파일 Environment variables 설정

### ISSUE THREAD

**Issue by Oh3gwnn** [Oh3gwnn/Project_Closetalk#41]
DB, Oauth2 관련 username, password, url(uri), jwt.secret 환경 변수 설정
현재 개인 정보가 노출되어 있으며 뿐만 아니라 나중 서버 정보까지 노출될 가능성이 커서 환경변수 설정이 필요할 것 같습니다.

방법을 몇 가지 생각해오긴 했는데
1. secret.yaml 파일을 생성하여 이 부분만 .gitignore에 추가
2. application.yaml 자체를 .gitignore에 추가
3. application.yaml에 대한 환경 변수 설정

개인적으로 3번째 방법을 추천하는 바 입니다.
(서로 계정 정보만 있다면 코드 자체를 수정할 필요가 없고, yaml 파일에 대한 공유 또한 쉽게 되기 때문)

**Comment by bluelily555** [comment]
3번 환경 변수 설정으로 변경 완료했습니다.
메일 발송관련 부분이 환경변수 처리가 되어있지 않아 해당 부분도 환경변수로 변경하겠습니다.
