### ISSUE TITLE
CLTK-35 : Commit, Push 관련 (isHidden 수정)

### ISSUE THREAD

**Issue by Oh3gwnn** [Oh3gwnn/Project_Closetalk#42]
제가 isHidden 값 변경 로직이랑 isHidden 값에 따라 옷장, 옷장 아이템 조회를 변경했습니다. 
근데 따로 브랜치 빼고 풀리퀘스트를 날렸어야 했는데 35번에서 그대로 commit, push 진행해버렸습니다...

closet 관련 수정 제외하고는 아래 2개만 변경되었는데 확인 부탁드립니다.

> **`UserRepository`** : _Optional\<UserEntity> findByNickname(String nickname);_ 추가
> **`data.sql`** : CLOSET 쪽 data 수정

일단 죄송합니다ㅜㅜ 다음부터는 주의하겠습니다.

---

[**1. CLTK-35 : 옷장 업데이트 이름 변경, hidden 분리**](https://github.com/Oh3gwnn/Project_Closetalk/commit/699339a6c0d62badd9541fff5fa641cbafc3eb84)
- 옷장 업데이트 url을 분리, 이름 변경의 로직은 이전과 동일
- isHidden의 경우 Url이 "closet/{closetName}/hidden" 로 변경, 
파라미터 값을 받지 않고 request 시 해당 옷장의 isHidden 값을 확인 후 반대 bool 값을 주는 형식으로 변경

[**2. CLTK-35 : isHidden 값에 따른 옷장 아이템 목록 조회**](https://github.com/Oh3gwnn/Project_Closetalk/commit/79bb3f1f6f1754eafbdc4ccf1c77152935695f7f) 

- EntityRetrievalService : getUserEntityByNickname 추가
- url에 nickname 추가 후 접근은 누구나 가능, 
하지만 isHidden == true 또는 해당 nickname의 user와 authentication 정보가 일치하지 않으면 목록 조회 실패

[**3. CLTK-35 : ishidden 값에 따른 closet Item 조회**](https://github.com/Oh3gwnn/Project_Closetalk/commit/0dd404bb7a68ea136006979a29b9b714498b0862) 

- url -> 이전 옷장 조회에 맞춰 /closet/{nickname}/{closetName}/{itemId}

**4. 그 외 수정사항**
- [CLTK-35 : nickname으로 user 찾기 추가](https://github.com/Oh3gwnn/Project_Closetalk/commit/11bc53e1ad030b8b2b3e73141b66dea0a691a617)
- [CLTK-35 : closet 관련 데이터 수정](https://github.com/Oh3gwnn/Project_Closetalk/commit/67458a266c7644a6c1acee9f247596d562f81566)
- [CLTK-35 : nickName -> nickname 수정](https://github.com/Oh3gwnn/Project_Closetalk/commit/f092193e0f7495575956a182d07d6b456c779715)

**Comment by hunirin** [comment]
확인했습니다

**Comment by bluelily555** [comment]
확인했습니다
