### ISSUE TITLE
CLTK-46 : Comment Soft Delete 관련 + LocalDateTime

### ISSUE THREAD

**Issue by Oh3gwnn** [Oh3gwnn/Project_Closetalk#46]
댓글 삭제 구현을 Soft Delete로 하기로 회의 당시 결정했었습니다.

구현은 delete_at 변수를 추가하고 null일 때는 삭제되지 않은 댓글,
삭제되었을 때는 localdate 데이터를 넣으려고 합니다.

추가로 현재 community 게시물들의 모든 시간 타입이 Localdate로 되어있는데,
Localdate의 경우 년월일만 가져오기 때문에 Localdatetime을 사용해야 할 것 같습니다.
이 부분은 현재 Community Article의 RUD 부분을 담당하고 계시는 영섭님의 코드가 마무리 되면 진행해보려고 합니다.

혹시 다른 의견 있으시면 댓글 달아주시면 감사하겠습니다.

**Comment by bluelily555** [comment]
확인했습니다. OOTD쪽 댓글도 `LocalDateTime`으로 deleted_at 추가해서 진행하겠습니다.

**Comment by Oh3gwnn** [comment]
넵 댓글 삭제 부분 구현 완료했습니다.
