### ISSUE TITLE
CLTK-45 : OOTD 상세페이지 디자인 초안

### ISSUE THREAD

**Issue by hunirin** [Oh3gwnn/Project_Closetalk#48]
![image](https://github.com/Oh3gwnn/Project_Closetalk/assets/112803923/c59343e7-877a-44f2-b2f5-f93962dac2ef)

임시로 작성한 초안인데 수정, 보완해야할 점 있으면 말씀부탁드립니다.

네비게이션은 불필요한 것 같아 임시로 빼놓았습니다

**Comment by Oh3gwnn** [comment]
깔끔하고 보기 좋은것같습니다.
갑자기 생각난건데 저도 댓글에 프로필사진 구현하는거 까먹은거같아서 풀리퀘 풀고 다시해야겠네요

**Comment by bluelily555** [comment]
사진이랑 내용 사이 경계선이 없으면 좋을 것 같은데 보기에 너무 구분이 안될까요?

**Comment by hunirin** [comment]
> 사진이랑 내용 사이 경계선이 없으면 좋을 것 같은데 보기에 너무 구분이 안될까요?

![image](https://github.com/Oh3gwnn/Project_Closetalk/assets/112803923/86ac7c14-5498-4ed7-b96e-14c4471817d9)

개인적으로는 구분선있는게 더 낫긴한데 어느게 더 나을까요

**Comment by youngseobkim** [comment]
저는 없는 편이 괜찮아보이네요

**Comment by hunirin** [comment]
넵 없는 쪽으로 진행하겠습니다!
